import "~/styles/globals.css";
import "@radix-ui/themes/styles.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";
import { Theme } from "@radix-ui/themes";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geist.variable}`}>
      <body>
        <Theme
          appearance="light"
          accentColor="violet"
          grayColor="slate"
          radius="medium"
          scaling="100%"
        >
          {children}
        </Theme>
      </body>
    </html>
  );
}
